### ISSUE TITLE
Audio file downloaded is .opus

### ISSUE THREAD

**Issue by someguydowntheroad555** [vitorgalvao/download-media-workflow#3]
When downloading any audio, it defaults to a .opus file.

**Comment by vitorgalvao** [comment]
You can change that in the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/).

In the future, please don’t skip the issue template.

**Comment by utsur0** [comment]
> You can change that in the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/).
> 
> In the future, please don’t skip the issue template.

Edit: The advanced section conflicts with the dropdown above. If the advanced section changes you should respect that and nullify the dropdown. Its very weird that its still in effect (for audio only). This caused me issues and was probably the reason for OPs initial issue rather than a lack of not using the setup flow.

**Comment by vitorgalvao** [comment]
> If the advanced section changes you should respect that and nullify the dropdown. It's very weird that it's still in effect (for audio only). This caused me issues

You have to consider other users, not your use case alone. **This works like it does by popular demand.** Most people have no idea (or interest in learning) how to set up advanced configuration *which affects both audio and video* but they do have specific needs for downloading audio. It doesn’t make sense to always download audio as M4A just because your video settings are `bestvideo[ext=mp4]+bestaudio[ext=m4a]/best`, when what you really want is a single MP3 file.

If I made it work like you suggest, I’d have a ton of confused users (instead of just one, over a decade after the first release) asking for it to be changed back. If the advanced configuration overwrote the audio dropdown, there would be no point to having the latter.

> was probably the reason for OPs initial issue rather than a lack of not using the setup flow.

I didn’t say they had the problem for skipping the template, that wouldn’t make sense. I asked them to not skip it because it has information needed for a proper diagnosis and so I don’t have to guess intentions and what someone probably meant. It’s good form to be mindful of other’s people time and provide as much information as one can when asking for help.

**Comment by utsur0** [comment]
I understand that most users wont touch it nor was my suggestion to remove the popular dropdown. Simply I was saying: **If the advanced configuration is in fact changed, ignore the dropdown.** 
 
Doubt that would cause confusion and helps both camps. Fair enough though, its ya workflow and works as-is. 

> proper diagnosis and so I don’t have to guess intentions and what someone probably mean

As far as template, true as rule of thumb. Caveat is most users (like OP) probably won't use GitHub and just register to comment their one-off issue—so its moot. But you're right though, doesn't hurt to try lol

**Comment by vitorgalvao** [comment]
> Simply I was saying: If the advanced configuration is in fact changed, ignore the dropdown.

I understand that. But again (emphasis added):

> If I made it work like you suggest, I’d have a ton of confused users (instead of just one, over a decade after the first release) asking for it to be changed back. **If the advanced configuration overwrote the audio dropdown, there would be no point to having the latter.**

The behaviour is unlikely to change, as it works exactly as the vast majority of people asked for.

> As far as template, true as rule of thumb. Caveat is most users (like OP) probably won't use GitHub and just register to comment their one-off issue—so it's moot.

In my experience, asking once is generally enough for people to do it. Either way it doesn’t matter anymore, you can no longer open an issue without a template.
